import { DataList, Modal, Tabs } from "@mantine/core";
import type { FrontendLicense } from "../types/frontend-license";

type Props = {
  frontendLicenses: FrontendLicense[];
  rustLicensesHTML: string;
  opened: boolean;
  onClose: () => void;
};

export const LicenseModal = ({ frontendLicenses, rustLicensesHTML, opened, onClose }: Props) => {
  return (
    <Modal opened={opened} onClose={onClose} title="Licenses" fullScreen>
      <Tabs defaultValue="frontend">
        <Tabs.List mb="xl">
          <Tabs.Tab value="frontend">Frontend Dependencies</Tabs.Tab>
          <Tabs.Tab value="rust">Rust Dependencies</Tabs.Tab>
        </Tabs.List>

        <Tabs.Panel value="frontend" mx="md">
          <DataList orientation="horizontal">
            {frontendLicenses.map((lib) => (
              <DataList.Item key={lib.name}>
                <DataList.ItemLabel miw={0}>{`${lib.name} (${lib.versions[0]})`}</DataList.ItemLabel>
                <DataList.ItemValue>{lib.license}</DataList.ItemValue>
              </DataList.Item>
            ))}
          </DataList>
        </Tabs.Panel>

        <Tabs.Panel value="rust" mx="md">
          {/* biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by cargo-about */}
          <div dangerouslySetInnerHTML={{ __html: rustLicensesHTML }}></div>
        </Tabs.Panel>
      </Tabs>
    </Modal>
  );
};
